backend:
  name: git-gateway
  branch: main

media_folder: "_site/images/uploads"
public_folder: "/images/uploads"

<<<<<<< HEAD
slug:
  clean_accents: true

=======
>>>>>>> parent of 8077ff2... Contrain images to 100% of post width
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "From", name: "from", widget: "select", options: ["큰 미밍", "작은 미밍"] }
      - { label: "Letter", name: "body", widget: "markdown" }